### ISSUE TITLE
Update PaLM Docs to reflect Vertex AI default

### ISSUE THREAD

**Issue by huangjeff5** [GoogleCloudPlatform/firebase-extensions#162]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: palm-firestore-chatbot, palm-firestore-gen-text, palm-firestore-summarize-text, firestore-semantic-search (`storage-label-videos`, etc)

### What feature would you like to see?

The docs still include this line:

```
⚠️ The PaLM API is currently in public preview. For details and limitations, see the [PaLM API documentation](https://developers.generativeai.google/guide/preview_faq).
Please ensure that you have already signed up for the [waitlist](https://makersuite.google.com/waitlist) and have been approved before installing the extension.
```

We should remove this from the top because Vertex AI is GA already and doesn't require waitlist.

Possibly let's add a smaller warning that says if you're using the Developer PaLM API, you still need to sign up for the waitlist. Use Vertex AI for production use cases.

**Comment by cabljac** [comment]
https://github.com/GoogleCloudPlatform/firebase-extensions/pull/158/files

I had merged this in which addresses this, but feel free to review the wording/formatting etc to check it's OK?
