### ISSUE TITLE
[Chatbot with PaLM API] Errors happen after ~25 documents in the collection

### ISSUE THREAD

**Issue by MarkTechson** [GoogleCloudPlatform/firebase-extensions#170]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: `googlecloud/firestore-palm-chatbot`  (`storage-label-videos`, etc)
- Extension version: `0.1.5`
- Configuration values (redact info where appropriate):
  - Palm API Provider
  -- generative

  - Collection Path
  -- discussions

  - Prompt Field
  -- prompt

  - Response Field
  -- response

  - Order Field (Optional)
  -- Parameter not set

  - Cloud Functions location
  -- us-central1

  - Language model
  -- chat-bison

  - Context (Optional)
  -- Parameter not set

  - Temperature (Optional)
  -- Parameter not set

  - Nucleus sampling probability (Optional)
  -- Parameter not set

  - Sampling strategy parameter (Optional)
  -- Parameter not set

  - Candidate count (Optional)
  -- 1    

  - Candidates field (Optional)
  -- candidates

  - Enable per document overrides.
  -- no

### [REQUIRED] Step 3: Describe the problem
Palm API extensions starts erroring out after a certain number of documents are added to the collection. After around 24 documents in the `discussions` collection, an error starts to happen:
```
Error message:

An error occurred while processing the provided message, 3 INVALID_ARGUMENT: Request payload size exceeds the limit: 20000 bytes.
```

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.
Add more than 24 documents to a single collections with the prompt field (so Palm can answer).

##### Expected result
Palm updates the document with a reply
##### Actual result
Palm updates the document with an error

**Comment by cabljac** [comment]
Ah OK I see the issue i think, we need to manually cut off the history before sending to PaLM. Thanks for raising! Will fix asap
