### ISSUE TITLE
[palm-secure-backend] VertexAI support

### ISSUE THREAD

**Issue by davidmigloz** [GoogleCloudPlatform/firebase-extensions#171]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **palm-secure-backend**

### What feature would you like to see?

I see that the rest of the PaLM-related extensions have been reworked to support both VertexAI and Generative AI for Developers PaLM API providers ([ref](https://github.com/GoogleCloudPlatform/firebase-extensions/pull/158/files)). However, I haven't seen that work being applied to `palm-secure-backend` as well. Are you planning to support VertexAI in `palm-secure-backend` extension?

### How would you use it?

I'm the maintainer of [LangChain.dart](https://github.com/davidmigloz/langchain_dart/commits/main/packages/langchain). `palm-secure-backend` is a very useful extension if you want to develop an LLM-powered app without having to setup a proxy server on your own backend. Using Flutter + LangChain.dart + palm-secure-backend extension enables the implementation of quite some LLM-powered use cases. MarketSuite/Generative AI for Developers is still not generally available, while VertexAI PaLM API is.

**Comment by pr-Mais** [comment]
Thanks for filing this request, @davidmigloz! This extension is designed as a secure wrapper around the PaLM Developers API, so supporting Vertex PaLM API currently is not on the roadmap.

**Comment by davidmigloz** [comment]
Too bad that PaLM Developers API is still not available in Europe 🙂
