### ISSUE TITLE
[speech-to-text] Add an option to move, transcribed text to firestore

### ISSUE THREAD

**Issue by byaruhaf** [GoogleCloudPlatform/firebase-extensions#175]
[READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a specific extension in this repository. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

[REQUIRED] Step 2: Extension name

speech-to-text

What feature would you like to see?

Add an option to move, transcribed text to firestore

How would you use it?

My plan is to use the summarize API to summarize the text in firestore

**Comment by cabljac** [comment]
thanks! I originally had this planned as a feature, but we removed it. I will look into it and discuss with the team

**Comment by dackers86** [comment]
Fixed by https://github.com/GoogleCloudPlatform/firebase-extensions/commit/14df3631d1e5e1bc07f95dcda41b485c026b009d

**Comment by byaruhaf** [comment]
This is awesome Thanks @dackers86 @cabljac going to check it out

**Comment by byaruhaf** [comment]
Sorry disturbing but is this in an upcoming version, I have version 0.1.4 and I don't see this option. 

<img width="900" alt="image" src="https://github.com/GoogleCloudPlatform/firebase-extensions/assets/4116539/140d2351-fe65-4939-9885-eac69ffc5b2d">

**Comment by dackers86** [comment]
Hi @byaruhaf 

This is looking to be released sometime this week!
