### ISSUE TITLE
Make Safety Settings Configurable

### ISSUE THREAD

**Issue by jtmuller5** [GoogleCloudPlatform/firebase-extensions#176]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **firestore_palm_gen_text**

### What feature would you like to see?

It would be nice to be able to configure the [safety settings](https://developers.generativeai.google/guide/safety_setting) for the Language Tasks with PaLM API extension. We can configure these settings in the API directly and in MakerSuite but not in Firebase.

### How would you use it?

I am trying to use Firebase extensions to extract data from documents that contain a few medical terms but the output is being blocked ~50% of the time. I have the temperature of my extension set to 0.

<img width="565" alt="image" src="https://github.com/GoogleCloudPlatform/firebase-extensions/assets/47997351/d78147f3-d0ff-40a6-9721-f0a03fa7fa3f">

**Comment by cabljac** [comment]
Sorry, the PR https://github.com/GoogleCloudPlatform/firebase-extensions/pull/177 should have closed this i think. Closing as resolved. Feel free to reopen if there's still an issue with the latest version!
