### ISSUE TITLE
[palm gen text] Content is being block by filters dispite all thresholds set to Block None

### ISSUE THREAD

**Issue by Jacquesjh** [GoogleCloudPlatform/firebase-extensions#214]
### [READ] Step 1: Are you in the right place?

This happens with the Language Tasks with PaLM API extension. 

### [REQUIRED] Step 2: Describe your configuration

I am using version 0.1.8.

Extension configs: 
- Palm API Provider: Generative Language AI for Developers
- API Key: left as blank
- Language model: text-bison-001
- Temperature: 0.6
- Nucleus...: blank
- sampling: blank:
- Candidate count: 1
- Every threshold as Block None

![image](https://github.com/GoogleCloudPlatform/firebase-extensions/assets/61204659/a4b21915-38ae-46ae-a6ca-a794af8c6069)

### [REQUIRED] Step 3: Describe the problem

Dispite all threshold being to block none, the safety filter still is being set to Block low and above:
![image](https://github.com/GoogleCloudPlatform/firebase-extensions/assets/61204659/d532b0f8-8968-484b-b798-7938b20feb61)

I can only see this as a bug since i am using the Generative Language AI for devs and the thresholds should apply.

**Comment by cabljac** [comment]
hm im struggling to reproduce this, can you go to the extensions UI and check that the config values have been set correctly?

Extensions -> Language Tasks with PaLM API -> Extension configuration

does it look like this?

<img width="833" alt="Screenshot 2023-10-18 at 09 19 58" src="https://github.com/GoogleCloudPlatform/firebase-extensions/assets/32874567/0c8a0c00-6dbf-47ff-903c-12ae185b80f6">

**Comment by cabljac** [comment]
Oh nvm, just seemed to repro it! Just required a more violent prompt. I will investigate, this may actually be a mistake on my part for what the unspecified threshold does

**Comment by cabljac** [comment]
I see the issue :) will make a fix

**Comment by cabljac** [comment]
I've opened a PR with a fix, note though that some content *will* still be blocked, even with filters set to `BLOCK_NONE`, as specified in the PaLM docs:

<img width="913" alt="Screenshot 2023-10-18 at 11 28 39" src="https://github.com/GoogleCloudPlatform/firebase-extensions/assets/32874567/70bf95d2-8b33-46f4-ad35-ca02d00b8791">

[PaLM safety settings docs](https://developers.generativeai.google/guide/safety_setting)
