### ISSUE TITLE
[speech-to-text] transcription doesn't include punctuation.

### ISSUE THREAD

**Issue by jaden210** [GoogleCloudPlatform/firebase-extensions#216]
[READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a specific extension in this repository. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

[REQUIRED] Step 2: Extension name

speech-to-text

What feature would you like to see?

Even with the correct BCP-47 code (en-US) and Language Model (Default) I am not getting any auto punctuation in the transcription object. This becomes difficult when the text file is even a paragraph long. See images below for configuration.

How would you use it?

Punctuation is vital to use the transcription text in any meaningful way.

<img width="940" alt="Screenshot 2023-10-16 at 6 22 25 PM" src="https://github.com/GoogleCloudPlatform/firebase-extensions/assets/11722487/5c307e8a-aebb-49e4-9acd-c35750659ac3">

<img width="868" alt="Screenshot 2023-10-16 at 6 25 55 PM" src="https://github.com/GoogleCloudPlatform/firebase-extensions/assets/11722487/0bbc57a3-02a8-4f94-b0be-26128295d994">

**Comment by jaden210** [comment]
The second screenshot is directly from [https://cloud.google.com/speech-to-text/docs/speech-to-text-supported-languages](https://cloud.google.com/speech-to-text/docs/speech-to-text-supported-languages) which confirms en-US Default does in-fact support Automatic punctation.

**Comment by cabljac** [comment]
ah sorry, thanks! I will look into it this week.
