### ISSUE TITLE
[text-to-speech] path to audio is not written back to the firestore document

### ISSUE THREAD

**Issue by slk333** [GoogleCloudPlatform/firebase-extensions#248]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** (`Convert text to speech`, etc)
- Extension version: **\_**
- Configuration values (redact info where appropriate):
  - **\_**
  - **\_**

### [REQUIRED] Step 3: Describe the problem

the path to the cloud storage audio file is not written back to the document once the operation completes.

#### Steps to reproduce:

create a document in the relevant collection with the `text` field. Then, notice that the document is not updated once the audio is stored on storage

##### Expected result

it should write back the path, as mentioned in the extension summary:

https://extensions.dev/extensions/googlecloud/text-to-speech

##### Actual result
no path is written

**Comment by slk333** [comment]
The benefit of updating the firestore document with the path would be to real-time listen the document to know when the audio file is ready on cloud storage.

Otherwise, how can we know when the audio is generated?

**Comment by slk333** [comment]
<img width="476" alt="Screenshot 2023-11-02 at 20 16 29" src="https://github.com/GoogleCloudPlatform/firebase-extensions/assets/23578949/1fe5a538-569d-4cc0-a4e8-835cab6bd5cf">

please not the third bullet

**Comment by slk333** [comment]
I looked at the cloud function generated by the extension, and it's pretty clear it's not trying to write the storage path back into the document

extension generated cloud function:
```js
try {
        const speech = await processText(request);
        if (speech && speech.audioContent) {
          // Merge the address validity data with the address document.
          const fileExtension = getFileExtension(
            audioEncoding || config.audioEncoding
          );

          const fileName = config.storagePath
            ? `${config.storagePath}/${snap.id}${fileExtension}`
            : `${snap.id}${fileExtension}`;

          const bucket = admin.storage().bucket(config.bucketName);

          const file = bucket.file(fileName);
          await file.save(Buffer.from(speech.audioContent));

          return;
        }
      } catch (error) {
        throw error;
      }
    }
    return;
```

with that being said, is that a bug or is it intended. If it is intended, do I have to write another cloud function to listen to cloud storage changes and write back to firestore?

**Comment by cabljac** [comment]
Should be fixed in https://github.com/GoogleCloudPlatform/firebase-extensions/pull/279 and will go out in next release

**Comment by bakua** [comment]
> Should be fixed in #279 and will go out in next release

Hi. Did the fix ever get released? The `audioPath` is still not appearing. I would assume not because the extension version in the marketplace os 0.1.4 and in the main branch it is 0.1.5.

**Comment by cabljac** [comment]
Apologies, it should have been released. I am doing that now

**Comment by cabljac** [comment]
I've now published a new release, it should be available on the marketplace soon, thanks!
