### ISSUE TITLE
[firestore-semantic-search] queryIndex does not respect neighbors param

### ISSUE THREAD

**Issue by jbraunschweiger** [GoogleCloudPlatform/firebase-extensions#282]
### [READ] Step 1: Are you in the right place?

Yes.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firebase-semantic-search**
- Extension version: **0.1.7**
- Configuration values (redact info where appropriate):
  - **Embeddings method: `palm`**
  - **Distance measure type: `DOT_PRODUCT_DISTANCE`**
  - **Algorithm Config: `bruteForceConfig`**
  - **Approximate number of neighbors: `100`**

#### Steps to reproduce:
1. Install Extension 
2. Query index with param `neighbours` != `10`

##### Expected result
number of datapoints in results === `neighbors`

##### Actual result
number of datapoints in result === `10`

### Investigation

I tried to debug this myself but the lack of documentation and console visibility around Vertex AI, as well as the inconsistent spelling of `neighbor` vs `neighbour` in docs and code made it almost impossible. This is about as far as I was able to get:

```
const response = await axios.post(
      `https://${endpoint}/v1beta1/projects/${config.projectId}/locations/${config.location}/indexEndpoints/${indexEndpoint}:findNeighbors`,
      {
        queries: queries.map(query => query.toVertexQuery()),
        deployed_index_id: `ext_${config.instanceId.replace(/-/g, '_')}_index`,
        neighbor_count: searchResults,
      },
      {
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${accessToken}`,
        },
      }
    );
```
Query Index **correctly** passes `searchResults` (more confusing naming) into the `findNeighbors` request
The request returns 10 results, independent of the value of `searchResults`

This really seems like something that should be caught by test cases - so very possible I'm doing something wrong. Would appreciate some more knowledgable eyes on this.

**Comment by AlexZhidkov** [comment]
Hi @jbraunschweiger I've just installed it and getting this error:
` TypeError: Cannot destructure property 'index' of 'metdata.data(...)' as it is undefined.
    at updateIndexConfigHandler (/workspace/lib/functions/update_index_config.js:29:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) `

Have you seen it or it worked fine for you?

**Comment by jbraunschweiger** [comment]
Hi - @AlexZhidkov I didn't get that issue, but your turnaround time seems to fast for the index to have deployed. Is your index showing as deployed in GCP? Does your metadata doc in firebase have an index ore deployed_index_id field?

**Comment by AlexZhidkov** [comment]
Where do I see if index is deployed in GCP?
I don't see metadata doc in my firestore. There's  `_ext-firestore-semantic-search` collection  with `tasks.status: "PENDING"`
I guess, I have to wait for it to complete? How would I know when I can start using the search?

**Comment by jbraunschweiger** [comment]
When `Pending` changes to `Index_Deployed` your gtg. It can take a few hours not worth staring at XD

**Comment by AlexZhidkov** [comment]
I think the problem was that the `Browser key (auto created by Firebase)` API key was restricted to Websites. When I removed the restriction, the extension worked fine.
