### ISSUE TITLE
[firestore-palm-chatbot] Add support to chose "chat-bison@002" and "codechat-bison@002" models on model selector in config

### ISSUE THREAD

**Issue by nikdelvin** [GoogleCloudPlatform/firebase-extensions#326]
New version on Chat Bison was released in Decemder 2023 and it's quality good than previous version, can easy compare with ChatGPT-4. 

It's just a 5 minutes action to add new 2 cases in switch in config and we able to use Chat Bison 2.

**Comment by nikdelvin** [comment]
Sure, the link: https://cloud.google.com/vertex-ai/docs/generative-ai/learn/model-versioning

I'm taking about "chat-bison@002" released on December 6, 2023. I'm sure it is available for Vertex API.

And extension "firestore-palm-chatbot" supports using models from Vertex API, but the last extension update was 3 months ago, I guess developer don't update model list in configuration with new Bison Model.

That's issue only about it: Add new models for Vertex API provider.

We just need to add new models here: https://github.com/GoogleCloudPlatform/firebase-extensions/blob/def10bc6e9c40daa7af61fd52961c245938e7f24/firestore-palm-chatbot/functions/src/config.ts#L46

Also I've tried Gemini extension recently, but unfortunately in doesn't apply Context filed in Config, and in my case it's seems useless.

**Comment by pr-Mais** [comment]
We could remove the version and let it always choose [the latest model](https://cloud.google.com/vertex-ai/docs/generative-ai/learn/model-versioning#latest-models), e.g. `text-bison` since the 001 version is to be deprecated in July, I will raise this with the team, thanks for raising the issue.
