### ISSUE TITLE
(firestore-multimodal-genai): handling large images with gemini

### ISSUE THREAD

**Issue by cabljac** [GoogleCloudPlatform/firebase-extensions#332]
For large enough images gemini will fail, it has a limit 

https://cloud.google.com/vertex-ai/docs/generative-ai/multimodal/send-multimodal-prompts#image-requirements

This needs to be investigated, not sure whether this would be a bug or feature request yet.

One potential workaround is to do compression of images over a certain size.

**Comment by pr-Mais** [comment]
@cabljac was this solved in the image compression PR?
