### ISSUE TITLE
 [ext-firestore-semantic-search ] NOT_FOUND: Publisher Model

### ISSUE THREAD

**Issue by frnndwrms** [GoogleCloudPlatform/firebase-extensions#369]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: googlecloud/firestore-semantic-search
- Extension version: 0.1.7
- Configuration values (redact info where appropriate):
Fields in a Document to index(opcional)
No se configuró el parámetro
Do backfill?
false
Embeddings method
palm
PaLM embeddings model(opcional)
No se configuró el parámetro
Distance measure type
COSINE_DISTANCE
Algorithm config
bruteForceConfig
Approximate number of neighbors
100
Shard size
SHARD_SIZE_SMALL
Machine type(opcional)
e2-standard-2
Acceletaor type(opcional)
ACCELERATOR_TYPE_UNSPECIFIED
Accelerator Count(opcional)
1
Min replica count(opcional)
1
Max replica count(opcional)
1
Cloud Functions location
us-central1
Ícono note

#### Steps to reproduce:

1. 
I installed the extension and I added the firestore rules, and give the permits to vertex ai machine in audit for read and write according setup instructions. 
2. Then I run 
gcloud functions --project XXXX call ext-firestore-semantic-search-YYY-queryIndex --data '{"data": {"query":["I am a query"]}}'

but I got "error: '{"error":{"message":"INTERNAL","status":"INTERNAL"}}'
executionId: f0bt4jz6g2nl"

I got error log for 

 ext-firestore-semantic-search-16hw-queryIndex 

Unhandled error Error: 5 NOT_FOUND: Publisher Model `projects/querelo-prod/locations/us-central1/publishers/google/models/undefined` not found.
at .callErrorFromStatus ( /workspace/node_modules/@grpc/grpc-js/build/src/call.js:31 )
at .Object.onReceiveStatus ( /workspace/node_modules/@grpc/grpc-js/build/src/client.js:192 )
at .Object.onReceiveStatus ( /workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360 )
at .Object.onReceiveStatus ( /workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323 )
at undefined. ( /workspace/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94 )
at process.processTicksAndRejections ( node:internal/process/task_queues:77 )

I tried this several minutes after, and half hour after with same results. 

##### Expected result

Got document list of the requested query

##### Actual result

 '{"error":{"message":"INTERNAL","status":"INTERNAL"}}'
executionId: f0bt4jz6g2nl"

**Comment by jauntybrain** [comment]
Hi @frnndwrms, thanks for reporting this issue. I see that you selected `palm` as your Embeddings method but you didn't select the PaLM Embeddings model, which is required for the PaLM method. Could you please try reinstalling the extension with specified PaLM Embeddings model (`embedding-gecko`) and see if the issue persists?

<img width="449" alt="Screenshot 2024-02-23 at 1 39 36 PM" src="https://github.com/GoogleCloudPlatform/firebase-extensions/assets/105740958/76e29b12-3670-4772-a90e-224b516eabbe">

**Comment by nicjhall85** [comment]
Wow

**Comment by hygu98** [comment]
Choosing the Model Embedding fixed this issue for me but it's definitely not clear when configuring the Extension in Firebase Cloud Console.
