### ISSUE TITLE
Chcem funkciu zdielania displaya a kamier a externych kamier v priamom  čase pocas hovorenej konverzacie na pozadi v priamom čase.+schopnost oznacovania alebo zvyraznovania bodu na display  + Ikona-tlacidlo na on off funkcie. 

### ISSUE THREAD

**Issue by Juraj333** [GoogleCloudPlatform/firebase-extensions#375]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **\_** (`storage-label-videos`, etc)

### What feature would you like to see?

Describe the feature you would like to add, or how you'd like to see the extension change.

### How would you use it?

Tell us how you'd use this feature in your app.

**Comment by pr-Mais** [comment]
If you have any feature requests please feel free to open a new issue describing your request in English.

**Comment by Juraj333** [comment]
I want the function of sharing the display and cameras and external cameras in real time during a spoken conversation in the background in real time. + tagging ability

**Comment by cabljac** [comment]
Is this a request to add a feature to an existing extension, or a request for an entirely new extension?

**Comment by cabljac** [comment]
This doesn't sound like it would be within the scope of a firebase extension.

**Comment by Juraj333** [comment]
I don't understand how it doesn't sound? And how does it sound? How should
it sound? And why doesn't it sound like a firebase extension? I don't know,
I'm an amateur in

Dňa st 21. 2. 2024, 14:49 Jacob Cable ***@***.***> napísal(a):

**Comment by cabljac** [comment]
> I want the function of sharing the display and cameras and external cameras in real time during a spoken conversation in the background in real time. + tagging ability

It isn't clear how this relates to firebase extensions.

**Comment by Juraj333** [comment]
Mne nieje jasne ani co mi ma alebo co nema byt jasne...
