### ISSUE TITLE
neighbours arg not passed from HTTP request of firestore-semantic-search

### ISSUE THREAD

**Issue by MetcalfeTom** [GoogleCloudPlatform/firebase-extensions#389]
According to the `query_index` source code, we should be able to pass an integer number for the number of neighbours returned.

Somehow, this doesn't work when requesting the endpoint, e.g.

```json
{"data": {"query": ["this is a test"], "neighbours": 30}}
```

Still only returns 10 results. Can this be investigated?

https://github.com/GoogleCloudPlatform/firebase-extensions/blob/b718308cfde2ef71108ac7c26ae5ad67aa4f6ab9/firestore-semantic-search/functions/src/functions/query_index.ts#L35

**Comment by MetcalfeTom** [comment]
I see it was already rasied in https://github.com/GoogleCloudPlatform/firebase-extensions/issues/282

**Comment by pr-Mais** [comment]
@MetcalfeTom we're investigating it, thanks for raising! will keep track on #282

**Comment by jauntybrain** [comment]
This issue has been resolved with PR #391.
