### ISSUE TITLE
[firestore-semantic-search] the fields config param is too restrictive

### ISSUE THREAD

**Issue by dbanisimov** [GoogleCloudPlatform/firebase-extensions#39]
The FIELDS config param in the firestore-semantic-search extension is too restrictive and doesn't allow many commonly used field paths formats.

###  Describe your configuration

- Extension name: `firestore-semantic-search`
- Extension version: `0.1.1`
- Configuration values (redact info where appropriate):
  - e.g. `fields: displayName,fullName`

#### Steps to reproduce:

Attempting to add an extension (so far I've only tried the Firebase Console) and set the fields config parameter to anything containing non-lowercase field names results in an error:

```
Variables may only use lowercase letters from A to Z, and may only be separated by commas. Trailing commas and empty variable names are not allowed.
```

##### Expected result
The config parameter should allow more field paths formats, including those containing underscores, and uppercase letter. Both `snake_case` and `camelBack` are commonly used for namig Firestore fields

##### Actual result
Only lowercase a-z are allowed

The current validation regex and the error message are defined in the extensions manifest: https://github.com/GoogleCloudPlatform/firebase-extensions/blob/df5886a7dbd9f40e960cf169b7ce70f9e6e8a8e4/firestore-semantic-search/extension.yaml#LL234C1-L238C15

**Comment by pr-Mais** [comment]
Thanks for reporting this issue, you're right it should be less restrictive! rolling out a fix shortly

**Comment by huangjeff5** [comment]
@pr-Mais That regex change looks good, can we add it to the semantic search extension too?
