### ISSUE TITLE
[firestore-genai-chatbot]: wildcards in Firestore collection path not working

### ISSUE THREAD

**Issue by bengeois** [GoogleCloudPlatform/firebase-extensions#390]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-genai-chatbot
- Extension version: 0.0.9
- Configuration values (redact info where appropriate):
  - Firestore Collection Path : '*' or 'conversations.*'

#### Steps to reproduce:

- install extension with '\*' or 'conversations.\*' as value for Firestore Collection Path variable
- create a collection and a document with a prompt field
- the cloud function is not triggered and no response from gemini is added to the document

##### Expected result
As written in the documentation : "The collection path also supports wildcards, so you can trigger the extension on multiple collections, each with their own private conversation history.", the added document with a "prompt" property should trigger the gemini API

##### Actual result
Nothing happened

**Comment by jauntybrain** [comment]
Hi @bengeois! Firestore triggers have a special wildcard notation, i.e. `collection/{wildcard}` instead of `collection/*`.

Please refer to [this document](https://cloud.google.com/functions/docs/calling/cloud-firestore-1st-gen) talking about Firestore triggers and possible collection wildcards. 

Let me know if this helps!

**Comment by bengeois** [comment]
Hi @jauntybrain,
Thanks for providing clarification. I've tried with `{collection}` and it works.
The link you shared seems quite helpful.

This is not an issue anymore.
