### ISSUE TITLE
Language Tasks with PaLM API - API not Published

### ISSUE THREAD

**Issue by ydax** [GoogleCloudPlatform/firebase-extensions#40]
### Describe your configuration

- Extension name: **\_** Language Tasks with PaLM API
- Extension version: **\_** 0.1.2
- Relevant configuration settings: **\_** Firestore collection name: `generate` **\_** Prompt variable: `prompt`

### Describe the problem
It appears that this API hasn't yet been published by Google.

#### Steps to reproduce:
1. [Install the extension](https://extensions.dev/extensions/googlecloud/firestore-palm-gen-text) through the Firebase console
2. Create a document in the `generate` collection with the `prompt` variable set to a prompt
3. The result will have the `status` object with `state` = `ERRORED` and the following `error` value: "7 PERMISSION_DENIED: Generative Language API has not been used in project 602706101270 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/generativelanguage.googleapis.com/overview?project=projectId then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."

#### Attempts to Solve
1. Going to the suggested link to enable the API. Result: The API fails to load (see screenshot)
<img width="1085" alt="Screenshot 2023-05-11 at 3 48 53 PM" src="https://github.com/GoogleCloudPlatform/firebase-extensions/assets/13105985/5c476681-da0c-4e1a-8983-58fad34f1d27">
2. Installing the API via the Firebase Node.js CLI using the command 
`firebase ext:install googlecloud/firestore-palm-gen-text --project=projectId`
Results in the following error:

```
i  extensions: ensuring required API firebaseextensions.googleapis.com is enabled...
✔  extensions: required API firebaseextensions.googleapis.com is enabled

Error: Unable to find published extension 'googlecloud/firestore-palm-gen-text'. Run firebase ext:install -i to select from the list of all available published extensions.
```

##### Expected result
The extension uses the `prompt` value to generate text within the `generate` document.

##### Actual result
Error related to permission denied / no access to the API.

**Comment by ydax** [comment]
Hey @huangjeff5 Yep I did that yesterday. I've never experienced a rollout like this with Firebase Extensions (where the Extension is available but the API it hits isn't yet) so I wasn't expecting to run into this issue.

**Comment by huangjeff5** [comment]
Gotcha, so just to double check, you received confirmation that you have been given access?

**Comment by ydax** [comment]
No, I haven't yet. FWIW we're also part of the Google for Startups program. If you can help out, our waitlist is under simulationsnet@gmail.com (I'll come back and redact this later). But I just wanted to let y'all know that this is happening because it was part of the big AI announcement yesterday, so I'm assuming lots of devs like me will be trying to use this these new PaLM extensions.

**Comment by huangjeff5** [comment]
Gotcha, thanks for the callout, maybe we should update the top line of our docs. Could you check if you've been approved now?

**Comment by ydax** [comment]
Got it. Thanks @huangjeff5!
