### ISSUE TITLE
Firebase semantic search extension, supported field types for indexing, support for sub collections

### ISSUE THREAD

**Issue by leykun10** [GoogleCloudPlatform/firebase-extensions#410]
I have two questions that i could not find an answer in the documentation.

1. What data type of fields in a collection can be indexed?

2. Can we index a sub collection or it should be a root collection? if so how do we pass it to the form when we install the extensions.

**Comment by leykun10** [comment]
@jauntybrain can you refer me to any doc if available.

**Comment by jauntybrain** [comment]
Hi @leykun10!

1. All types are indexed - if the value type is a `string`, then it is used as-is, otherwise the field value is jsonified.

2. The extension currently does not support subcollections, so the root collection must be passed.

Please let me know if this helps.

**Comment by JGSolutions** [comment]
Can we use multiple input fields when using the firebase extension. 

In the extension doc it says

> Input field name
> What is the name of the field that contains the string that you want to embed?

**Comment by leykun10** [comment]
@jauntybrain Yeah got it!
