### ISSUE TITLE
bigquery-firestore-export - unable to create transferConfig

### ISSUE THREAD

**Issue by sjerzak** [GoogleCloudPlatform/firebase-extensions#411]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_bigquery-firestore-export**
- Extension version: **\_0.1.4**

### [REQUIRED] Step 3: Describe the problem

Extension is unable to create transferConfig
![image](https://github.com/GoogleCloudPlatform/firebase-extensions/assets/6871723/192dd3c3-902c-40f0-aea4-27071bb8ef7e)

#### Steps to reproduce:

Install and config extension. It will stuck on 
![image](https://github.com/GoogleCloudPlatform/firebase-extensions/assets/6871723/c64b4fca-0fd4-4481-b3b4-bef3c845acba)

##### Expected result
TransferConfig created.

##### Actual result
Hang on "Creating a new transfer config and scheduling the query." status.

**Comment by jauntybrain** [comment]
Hi @sjerzak, thank you for reporting this issue. I am working on reproducing it but I need a bit more information.

Could you please verify if the Firestore collection that you specified during extension installation (defaults to transferConfigs) contains a document with a field `name`? If it does, could you please share the value of that field?

**Comment by sjerzak** [comment]
Hi

Thanks for checking on this.

I did some more checks and it seems that the issue occurs when I'm trying to use collection that already exists.
I've change extension settings back to use default transferConfigs collection and extension was able to create that collection with proper document containing fields (name etc...), then TransferConfig was created properly.

Answering your question I wasn't able to find document with a field `name` in collection specified by me before reverting to transferConfigs collection.

**Comment by jauntybrain** [comment]
@sjerzak thanks for the information! Yes, the specified collection must either be empty or contain a previously used transfer config, since it should only contain information about BigQuery transfers. We will make sure to highlight this in the documentation.

**Comment by sjerzak** [comment]
Could you please double check if "or contain a previously used transfer config" functionality is working correctly?
I reconfigured extension using `transferConfigs` collection, only thing I did change was `Function memory(Optional)` and it stuck on  `ext-bigquery-firestore-export-upsertTransferConfig` again.
![image](https://github.com/GoogleCloudPlatform/firebase-extensions/assets/6871723/e601b6ac-3220-4819-8ba0-d452b5aabcf7)

After deleting Firebase collection `transferConfigs` and manually removing BQ `Data transfers` extension worked as expected.
BQ `Data transfers` was added and Firestore collection `transferConfigs` were created.

**Comment by jauntybrain** [comment]
@sjerzak thanks for reporting this! I made a PR that resolves this issue.
