### ISSUE TITLE
[firestore-semantic-search] unable to configure

### ISSUE THREAD

**Issue by afirstenberg** [GoogleCloudPlatform/firebase-extensions#46]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your configuration

- Extension name: Semantic **Search with Vertex AI**
- Extension version: **0.1.2**
- Configuration values (redact info where appropriate):
  - **N/A**

#### Steps to reproduce:

* Install extension from Firebase Console
* In Step 2 (Install and Authorize This Extension: Review APIs enabled and resources created) there is no Next button enabled
* Click on Step 3 header. Click on Next.
* In Step 4 (Configure extension) there is no text following it or next button or anything

##### Expected result

Something about configuring it?

##### Actual result

Appears to be a dead end

**Comment by dackers86** [comment]
Closing as workaround provided, with a potential platform update fixing this in the future.
