### ISSUE TITLE
Clarity on Model Naming Conventions

### ISSUE THREAD

**Issue by ydax** [GoogleCloudPlatform/firebase-extensions#508]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** Multimodal Tasks with the Gemini API
- Extension version: **\_** 1
- Configuration values (redact info where appropriate):
  - **\_** Gemini model: gemini-pro

### [REQUIRED] Step 3: Describe the problem
The extension doesn't seem to use the Vertex model naming conventions. For example, `gemini-pro`, the default model name, is nowhere to be found in the [linked models docs](https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models). `gemini-1.0-pro` is there and so is `gemini-1.5-pro`, but no `gemini-pro`. So which model are we getting? How can we ensure use of, for example, `gemini-1.5-pro`?

These naming conventions need to line up.

##### Expected result
I'd recommend that the parameter value for "Gemini model" for this extension line up with the API model names like `gemini-1.5-pro` that are listed in the docs so that devs can clearly select their preferred model.

**Comment by pr-Mais** [comment]
Hi @ydax, thanks for your valuable report. The extension allows free-text form for the model name, the one you mentioned `gemini-pro` is only a default value that you can change, there's no other specified models inside the extension. Linked a PR to update the default value to `gemini-1.0-pro` which supports the latest stable version of Gemini 1.0 on both Google AI and Vertex AI.

**Comment by ydax** [comment]
awesome, thanks for clarity. So does that mean that we can use the other model names as seen in the Vertex docs? I tried these model names before and the extension threw an error.

**Comment by mrroccodev** [comment]
Hi @pr-Mais . I have tried to use these model names and got this error:
gemini-1.5-flash
gemini-flash

What are the list of available models supported?

GoogleGenerativeAIError: [404 Not Found] models/gemini-flash is not found for API version v1, or is not supported for GenerateContent. Call ListModels to see the list of available models and their supported methods.
    at makeRequest (/workspace/node_modules/@google/generative-ai/dist/index.js:216:19)

**Comment by pr-Mais** [comment]
@mrroccodev thanks for reporting your issue, we would need to update the API version used by the extension to support newer models & document the supported list, working on it.
