### ISSUE TITLE
[Bug] Maybe `Singapore (asia-southeast1)` missed?

### ISSUE THREAD

**Issue by zerolethanh** [GoogleCloudPlatform/firebase-extensions#525]
At https://github.com/GoogleCloudPlatform/firebase-extensions/blob/4539343fa535c3cbbb21fdbdcfd24a8796fbb0c8/storage-reverse-image-search/extension.yaml#L629

I have selected location Singapore for my deploy but value is set to `value: asia-south1` . Is this missed setting?

**Comment by pr-Mais** [comment]
Thanks for raising! This might be a typo, it should be `asia-southeast1`, looking into it. I think many extensions are affected by this.

**Comment by zerolethanh** [comment]
thanks for your reply, please fix that.
