### ISSUE TITLE
[firestore-semantic-search] the function must be called with one argument query containing the query text

### ISSUE THREAD

**Issue by jggomezt** [GoogleCloudPlatform/firebase-extensions#61]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your configuration

- Extension name: Semantic Search with Vertex AI
- Extension version: 0.1.4
- Configuration values (redact info where appropriate):
    N/A

### [REQUIRED] Step 3: Describe the problem

I have installed the extension successfully

Steps to reproduce:
- Call the function ext-firestore-semantic-search-queryIndex
- The body is 

```
{
    "data": {
        "query": [
            "What is your name"
        ]
    }
}
```

- The service responds
```
{
    "error": {
        "message": "The function must be called with one argument \"query\" containing the query text.",
        "status": "INVALID_ARGUMENT"
    }
}

```
##### Expected result
successfully

##### Actual result
```
{
    "error": {
        "message": "The function must be called with one argument \"query\" containing the query text.",
        "status": "INVALID_ARGUMENT"
    }
}

```

**Comment by pr-Mais** [comment]
Thanks for reporting, I can reproduce.
We will publish a new version with a fix soon.
