### ISSUE TITLE
[palm-secure-backend] Missing code samples

### ISSUE THREAD

**Issue by nohe427** [GoogleCloudPlatform/firebase-extensions#70]
The samples for the [palm-secure-backend](https://github.com/GoogleCloudPlatform/firebase-extensions/blob/main/palm-secure-backend/POSTINSTALL.md) do not point to real locations. The links used are [here](https://github.com/googlecreativelab/quickprompt) and [here](https://github.com/googlecreativelab/listit).

**Comment by huangjeff5** [comment]
What are the real locations?

**Comment by huangjeff5** [comment]
Links:
https://github.com/google/generative-ai-docs/tree/main/demos/palm/web/quick-prompt
https://github.com/google/generative-ai-docs/tree/main/demos/palm/web/list-it
