### ISSUE TITLE
storage-transcode-videos no longer installs properly

### ISSUE THREAD

**Issue by almazancameron** [GoogleCloudPlatform/firebase-extensions#93]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **storage-transcode-videos**
- Extension version: **0.0.1**
- Configuration values (redact info where appropriate):
  - **Not really relevant to the issue**

### [REQUIRED] Step 3: Describe the problem
I installed this extension less than a week ago for use in my project. In an attempt to fix an error that suddenly popped up, I uninstalled the extension, assuming I would be able to reinstall it immediately afterwards. Now I'm not even able to install the extension.
#### Steps to reproduce:
Try to install storage-transcode-videos to a firebase project via this link (which btw is no longer on the readme, and the extension doesn't show on extensions.dev so you have to look in the commit history of the readme to find this) https://console.firebase.google.com/project/_/extensions/install?ref=googlecloud/storage-transcode-videos

##### Expected result
The extension is successfully installed
##### Actual result
Extension install fails with error: 
`; RESOURCE_ERROR at /deployments/firebase-ext-storage-transcode-videos/resources/transcodevideo: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Unable to retrieve the repository metadata for projects//locations/us-central1/repositories/gcf-artifacts. Ensure that the Cloud Functions service account has 'artifactregistry.repositories.list' and 'artifactregistry.repositories.get' permissions. You can add the permissions by granting the role 'roles/artifactregistry.reader'.","status":"PERMISSION_DENIED","statusMessage":"Forbidden","requestPath":"https://cloudfunctions.googleapis.com/v1/projects/viscap-plus/locations/us-central1/functions","httpMethod":"POST"}}`

**Comment by cabljac** [comment]
Hi there, just want to clarify,

> Extension name: storage-transcode-videos (storage-label-videos, etc)

The problem you're having is with `storage-transcode-videos`? Or `storage-label-videos` as well?

**Comment by almazancameron** [comment]
Apologies, the problem is with storage-transcode-videos only, and for additional clarification, this error persists even if the service account has the permission specified in the error (I even tried setting the service account to owner as well)

**Comment by cabljac** [comment]
Thanks, I will raise this with the team today, as this extension doesn't seem explicitly published.

**Comment by cabljac** [comment]
In the meantime, if it's urgent, you could try to install from a local source, if you have `Node.js` and `firebase-tools` installed globally:

1. Clone this repo
2. From the root directory run `cd storage-transcode-videos && npm install & npm run build`
3. From a directory initialised with your firebase app (containing a firebase.json etc):
```firebase ext:install <path to storage-transcode-videos directory> --project=<your project id>```
4. After following the prompts to configure the extension, you can then deploy to your project by running the following from the same location:
 ```firebase deploy --only extensions --project=<your project id>```
 
(I will attempt this now anyway and let you know if it works)

**Comment by cabljac** [comment]
Yeah the above process seems to work for me. If you attempt it and have issues let me know. I'll let you know any updates regarding a new install link.

**Comment by almazancameron** [comment]
Sorry, as it turns out, our billing account was disabled temporarily and after re-enabling it the extension works as expected...

Thanks so much for the quick response.
