### ISSUE TITLE
[text-to-speech] Empty Language code

### ISSUE THREAD

**Issue by devandanger** [GoogleCloudPlatform/firebase-extensions#99]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: text-to-speech
- Extension version: *=0.1.3
- Configuration values (redact info where appropriate):

us-central1
Document Path: tts_content
Location: mighty-strong-software-apps.appspot.com
Storage path (Optional): tts_content
Enable ssml: no
Language code (Optional): en-US
Voice type (Optional): Standard
SSML Gender: FEMALE
Audio Encoding: MP3
Enable per document overrides: yes

#### Steps to reproduce:
I've configured the extension to work with both SSML and regular text but on creation of documents I continue to get the following log failures.

##### Expected result
I expect a good run here seeing as I specified the language code in the extension based on the drop downs.
##### Actual result
Continue to get failures with the following logs.

Error: 3 INVALID_ARGUMENT: Empty language code.
    at callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /workspace/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

**Comment by dackers86** [comment]
HI @devandanger 

I have tried to replicate with the same configuration, however the files appear to generate as expected.

As a solution for now, does overriding the config in the document resolve the issue, for example:

```js
{
   "text": "This is a test",
   "languageCode": "en-US"
}
```

**Comment by devandanger** [comment]
Yes this worked.  It continues to be really finicky though on how it's generating but at least it generating now.

for eg..
![image](https://github.com/GoogleCloudPlatform/firebase-extensions/assets/718744/24e1444b-a96c-45ce-82ad-4650d061b481)

This generated media read by the female voice, but changing this to en-US I couldn't get the female voice working in that scenario.

**Comment by devandanger** [comment]
I think SSML Gender is getting ignored and the default for that languageCode is getting picked up.  So I think in general adding some more document to how the configurable overrides would be helpful.  I started looking through the code and unit tests to infer but I started going down a rabbit hole.

Thanks for the help though @dackers86

**Comment by dackers86** [comment]
Too add more to this investigation, this was successfully replicated with the vlaues:

{
   "text": "This is a test",
   "languageCode": "en-US",
    "voiceName": "en-US-Neural2-C"
}

Potential use case for investigating this issue.
